server:
  port: 8090

spring:
  application:
    name: June_SQL_CRUD
  datasource:
    url: jdbc:mysql://localhost:3306/june_sql_crud
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
